### ISSUE TITLE
onReceiveLocation里得到结果直接onNext后直接onComplete是否可以

### ISSUE THREAD

**Issue by narakai** [dudu90/RxLocation#3]
请问subscriber.unsubscribe()是何时执行的呢，如果onReceiveLocation里得到结果直接onNext后直接onComplete是否可以？

**Comment by dudu90** [comment]
RxLocation只作为数据源，怎么处理交给业务逻辑.

**Comment by dudu90** [comment]
@narakai RxLocation只作为数据源，怎么处理交给业务逻辑.

**Comment by narakai** [comment]
谢谢解答
